# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.1
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args:
            - "--max-line-length=88"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    -   id: mypy
        args: [
            "--ignore-missing-imports",
            "--scripts-are-modules",
            "--disallow-untyped-defs",
            "--disallow-untyped-calls"
            ]
        exclude: "tests"
-   repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    -   id: nbstripout
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest --cov=he_man_tenseal --cov-report html
        language: system
        pass_filenames: false
        always_run: true
