[tool.poetry]
name = "he-man-tenseal"
version = "0.1.0"
description = "he-man-tenseal"
authors = ["David Drexel, Alessio Montuoro, Martin Nocker, Michael Rader"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
tenseal = "^0.3.14"
click = "^8.1.7"
onnx = "^1.16.0"
loguru = "^0.7.2"
pydantic-settings = "^2.2.1"
onnxruntime = "^1.17.3"
jsonschema = "^4.21.1"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
pytest-cov = "^5.0.0"
torchvision = "^0.17.2"
ipython = "^8.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
he-man-tenseal ="he_man_tenseal.main:command_line"
